version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "paper-18"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tu4pm01hbisf"
s3_prefix = "paper-18"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
